# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.4.4"
wally = "upliftgames/wally@0.3.2"
wally-patch-package = "Barocena/wally-patch-package@1.2.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
luau-lsp = "JohnnyMorganz/luau-lsp@1.35.0"
stylua = "JohnnyMorganz/stylua@2.0.1"
testez-companion-cli = "jacktabscode/testez-companion-cli@0.1.4"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
