name: Release
on:
  workflow_dispatch:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build-and-release-github-version:
    runs-on: Windows-Latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Setup node v20.8.1
        uses: actions/setup-node@v2
        with:
          node-version: 20.8.1
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install node modules
        run: npm i

      - name: Install node CI modules
        run: npm ci

      - name: Login to wally
        run: wally login --token $env:WALLY_TOKEN
        env:
          WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}

      - name: Release GitHub
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy project
        run: rojo upload model.project.json --asset_id ${{ vars.ASSET_ID }} --cookie $env:ROBLOSECURITY
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
