name: Release
on:
  workflow_dispatch:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: Windows-Latest
    needs: build
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Test
        run: echo %cavalo%
        env:
          cavalo: 10

      - name: Deploy project
        run: rojo upload model.project.json --asset_id ${{ vars.ASSET_ID }} --cookie %ROBLOX_SECURITY%
        env:
          ROBLOX_SECURITY: ${{ secrets.ROBLOX_SECURITY }}

  release-github-version:
    runs-on: Windows-Latest
    needs: build
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout git files
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Aftman Tools
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: true

      - name: Download builded model
        uses: alehechka/download-tartifact@v2
        with:
          name: model-build

      - name: Setup node v20.8.1
        uses: actions/setup-node@v2
        with:
          node-version: 20.8.1
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install node modules
        run: npm i

      - name: Install node CI modules
        run: npm ci

      - name: Release GitHub
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}
